spring:
  application:
    name: MobileBankingSystem

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: 1234

  # 静态文件？

  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: /static/**

  # 文件大小
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

# 端口号
server:
  port: 8080

# mybatis-plus
mybatis-plus:
  configuration:
    # ??
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  global-config:
    # ????
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
  mapper-locations: classpath:com/ccnu/mobilebank/mapper/xml/*.xml

# ??
logging:
  level:
    web: debug
    sql: debug

# Redis 连接信息
redis:
  host: 127.0.0.1
  port: 6379

